spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
app:
  frontend:
    url: ${FRONTEND_URL}
  jwt:
    secret: ${JWT_SECRET}
  initial:
    admin:
      email: ${ADMIN_EMAIL}
      password: ${ADMIN_PASSWORD}
    lecturer:
      email: ${LECTURER_EMAIL}
      password: ${LECTURER_PASSWORD}
    student:
      email: ${STUDENT_EMAIL_1}
      password: ${STUDENT_PASSWORD_1}
    student2:
      email: ${STUDENT_EMAIL_2}
      password: ${STUDENT_PASSWORD_2}
  resend:
    api:
      key: ${RESEND_API_KEY}