spring:
  application:
    name: campus-platform-service
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
app:
  frontend:
    url:
  jwt:
    secret: meinSuperGeheimesJwtSecretMitMindestens32Zeichen!
  initial:
    admin:
      email: admin@campusplatform.de
      password: admin
    lecturer:
      email: lecturer@campusplatform.de
      password: lecturer
    student: 
      email: student@campusplatform.de
      password: student
  defaults:
    theme: theme-azure
    brightness: light
  resend:
    api:
      key:
    from: "Campus Platform <email@campusplatform.de>"
